<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE model [<!ELEMENT model (entity*)>
	<!ATTLIST model name CDATA #REQUIRED>
<!ELEMENT entity (attribute*)>
	<!ATTLIST entity name CDATA #REQUIRED>
	<!ATTLIST entity subtype CDATA #IMPLIED>
<!ELEMENT attribute (typeList|type)>
	<!ATTLIST attribute name CDATA #REQUIRED>
<!ELEMENT typeList (typeList|type)>
	<!ATTLIST typeList type CDATA #REQUIRED>
<!ELEMENT type EMPTY>
	<!ATTLIST type type CDATA #REQUIRED >

]>
<model name="parser">
	
	<entity name="Satellite" subtype="Flotte">
		<attribute name="nom">
			<type type="String"/>
		</attribute>
		<attribute name="voisin">
			<type type="Satellite"/>
		</attribute>
		<attribute name="voisin2">
			<type type="Satellite"/>
		</attribute>
		<attribute name="id">
			<type type="Integer"/>
		</attribute>
	</entity>
	<entity name="Flotte">
		<attribute name="listS">
			<typeList type="Array">
				<type type="Satellite"/>
			</typeList>
		</attribute>
	</entity>
	
</model>